# Generated by Django 4.0.3 on 2022-03-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
