# Generated by Django 4.0.3 on 2022-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_backgroundpage_delete_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='backgroundPage',
        ),
        migrations.AlterField(
            model_name='noodle',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.FloatField(),
        ),
    ]
